service: crawler-processStreamUpdate

plugins:
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 15
  logRetentionInDays: 14
  versionFunctions: false

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: arn:aws:dynamodb:*:*:table/crawler

functions:
  streamUpdated:
    handler: handler.streamUpdated
    events:
      - stream: arn:aws:dynamodb:us-east-1:515804667357:table/crawler/stream/2019-02-06T21:09:09.888

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: crawler
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
        KeySchema:
          - AttributeName: url
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
